### ISSUE TITLE
差分が見れないので

### ISSUE THREAD

**Issue by yfujii01** [takayamazusa/igogame#1]
@takayamazusa 
visual studioが作ったc++のファイルは、UTF16というエンコードで表示されるのですが、そのままではgithub上で差分を比較することができません。
今後、c++のソースを管理する際は以下のファイルを作ってgit管理してgithubにpushしてもらえませんか。

[ファイル名]
```
.gitattributes
```
[内容]
```
*.cpp diff=utf16
```

これを作ってもらえるとレビューがやりやすくなります。

**Comment by takayamazusa** [comment]
@yfujii01 
da7d4e175244755b137b2ec1c654d9e7f1483459
社内メールでもご報告したのですが、
またお時間のある際にご確認をお願いいたします。

**Comment by takayamazusa** [comment]
@yfujii01 
030e8e2e4c7a8502d35e1ccfb8cde2974a0bde45
ConsoleApplication9.cppをpushしました。

**Comment by yfujii01** [comment]
@takayamazusa 
リンク先がまだBinary file not shown.のままですね。
もう一回、適当な修正をしてpushしてみてもらえますか？

**Comment by takayamazusa** [comment]
@yfujii01 
a56bd3505595a4d2dbf6bb2d02854b6113c1e598
再度pushいたしました。
ご確認をお願いします。

**Comment by yfujii01** [comment]
@takayamazusa 
すみません。このやり方はgithubではなくてローカルで比較するための方法のようでした。
github上で差分を表示させるのはファイル自体のエンコードを変えるしか無いようです。

**Comment by yfujii01** [comment]
@takayamazusa 
sjisにしてもらったことで ba3ef02b70fc220e8de7553fdfa66654b08e9a11 から差分が確認できるようになりました:bow:

.gitattributesは完全にいらないものになってしまったので削除しといてください。
